import { Inter } from "next/font/google";
import "./globals.css";

import ClientContainer from "./components/ClientContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl mx-auto`}>
        <ClientContainer>{children}</ClientContainer>
      </body>
    </html>
  );
}
